apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    tier: db
    project: expense
spec:
  replicas: 1
  matchlabels:
    app: mysql
    tier: db
    project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: chaitanyaj293/mysql:v1
---
apiVersion: v1
kind: Service
metadata:
  matchlabels:
    app: mysql
    namespace: expense
spec:
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
  - name: mysql-svc-port
    protocol: TCP
    port: 3306
    targetPort: 3306
